### ISSUE TITLE
Arch is pushing out some fixes for dbus activation in Systemd

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-openrc#10]
Do we need something similar for **openrc**?

[D-Bus now launches user buses](https://www.archlinux.org/news/d-bus-now-launches-user-buses/), [lxde-common](https://projects.archlinux.org/svntogit/community.git/commit/trunk?h=packages/lxde-common&id=042efd55e5a1f9c817e66f3e4d9354b5bf2595cb), [xfce4-session](https://projects.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/xfce4-session&id=a26336aba1b206a79d50ecd9795eb0289d6a5972)

**Comment by udeved** [comment]
Hmm, I don't know with lxde and xfce.
But I temporarily addressed this with dbus-openrc, basically 1.10.0-2 with dbus initscript.

**Comment by aadityabagga** [comment]
Possibly a xfce4-session-consolekit package that does not contain these custom dbus patches
