### ISSUE TITLE
versioning [dbus-openrc]

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-openrc#11]
Pamac on a freshly built stable ISO wants to update:
```
$ yaourt dbus-openrc
1 community/dbus-openrc 20150611-1 (openrc-base openrc-desktop) [installed: 1.10.0-1]
```

**Comment by udeved** [comment]
Thats normal, since dated version package will always try to upgrade versioned package.

**Comment by oberon2007** [comment]
hmm :stuck_out_tongue_closed_eyes:

**Comment by oberon2007** [comment]
Can we remove the old one somehow?

**Comment by udeved** [comment]
Nope, only after I have reworked AUR4.
I will remove any openrc from AUR in favor of installing buildtree on arch, from AUR.
Ie no direct openrc support on arch any longer.

**Comment by oberon2007** [comment]
Why not stick to dated versioning then? People will downgrade their fresh installs without realizing...

**Comment by udeved** [comment]
Because as I explained earlier, dbus-openrc has become a full build, due to the changes in the dbus package, which requires now a full build on openrc..
