### ISSUE TITLE
upower-pm-utils not providing libupower-glib.so.3

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-openrc#12]
xfce4-power-manager requires **libupower-glib.so.3**, which should be provided by upower.
upower-pm-utils is obviously not providing it.
```
xfce4-power-manager: error while loading shared libraries: libupower-glib.so.3: cannot open shared object file: No such file or directory
```

**Comment by philmmanjaro** [comment]
I don't get your issue here:
```
[phil@manjaro iso]$ pacman -Qo /usr/lib/libupower-glib.so.3
/usr/lib/libupower-glib.so.3 is owned by upower 0.99.3-1
```

**Comment by oberon2007** [comment]
Packages-Desktop: ``>openrc upower-pm-utils``
```
upower-pm-utils
Version        : 0.9.23-6
Provides       : upower=0.9.23
**Conflicts With : upower**  upower-nosystemd
```
libupower-glib.so.3 not present while upower-pm-utils is installed.

**Comment by philmmanjaro** [comment]
Now I get it. Which **libupower-glib.so** does it have then? Maybe we need a symlink then.

**Comment by oberon2007** [comment]
:) It has **libupower-glib.so.1.0.4**

**Comment by udeved** [comment]
Have you tried upower and pm-utils?
xfce is the only DE atm which has proper ck2 support afaik.
This mean, suspend and hibernate have moved away from upower, done by ck2 now, as opposed to upower-pm-utils, which is the last version of upower, which did the power management within upower.

So I recommend to test:
xfce
upower
ck2
pm-utils(needed by ck2)

**Comment by oberon2007** [comment]
Yes have tried. And my suggestion was to replace ``>openrc upower-pm-utils`` with ``>openrc pm-utils``
See https://github.com/manjaro/manjaro-tools-iso-profiles/issues/50

**Comment by udeved** [comment]
Remove it, but KDE for example will still need the older upower version locally then.
The ugly observation with kde, if I have kde-runtime(kde4) installed, suspend stops working if inactive.

**Comment by oberon2007** [comment]
ok. thanks!
