### ISSUE TITLE
dbus-openrc

### ISSUE THREAD

**Issue by archnous** [manjaro/packages-openrc#15]
Perhaps the depends element in dbus-openrc/PKGBUILD should be "libdbus=${pkgver}" instead of "libdbus>=${pkgver}"? I got the following error after testing/libdbus-1.10.2 was installed and no desktop session afterwards:

<code>dbus-daemon: /usr/lib/libdbus-1.so.3: version `LIBDBUS_PRIVATE_1.10.0' not found (required by dbus-daemon)</code>

**Comment by udeved** [comment]
Thanks nous.
The package transition on arch went ok I assume?

I would be interested to probably have the openrc optional modules-load-d.patch tested on arch.
It basically reads /etc/modules-load.d files and adds and newly writes the /etc/conf.d/modules before the service is started.  It can be activated in /etc/conf.d/modules when patched. Overall, with patch and activated, the /etc/conf.d/modules gets created on the fly.

**Comment by archnous** [comment]
The transition did require some manual intervention, or a single-user prompt awaited those who did -Su over openrc-core (me included, see http://systemd-free.org/news.php#151017). I've seen worse though.
About modules-load-d, I still have a systemd box at work I haven't converted, I'll try it there and report back.

**Comment by archnous** [comment]
Update: In the aforementioned systemd box (now ex-systemd) I had a modprobe.conf with a few 'blacklist' lines and a modules-load.d/e1000e.conf for the NIC module. The conf.d/modules was created containing only a 'modules="e1000e"' line. I don't know if the blacklisted modules were supposed to be there too though.

**Comment by udeved** [comment]
Thx nous, nope, the blacklisted modules remian in /etc/modprobe.d folder.
So it works as intended on arch it seems.
The patch has still some issue with mhwd and hybrid video devices, optimus chips and such.

**Comment by udeved** [comment]
Nous, I have read your discussion on arch forums.
No surprise there, you ran into an argument with Mr Alad, who bugged me on AUR.
You are more than welcome to join efforts on manjaro. :)

**Comment by archnous** [comment]
I've bumped into an argument more than once, to be precise, but I don't hold any grudges; my systems, my rules.

As I mention in the systemd-free.org's main page, "Manjaro OpenRC is my Linux of choice since I've had it with systemd. All my new linux installations are of this flavour, as I've become too accustomed to pacman (unless someday it depends on systemd-pacmand or something)."

However, my time is very limited to be a reliable team member; I just update the repo with the script Aaditya maintains and the news section of the site whenever I bump into problems. Nevertheless, If you think that there's something I could help, I'll be more than glad to if my time permits.
