### ISSUE TITLE
bumblebee-openrc needs to adopt current bumblebee changes

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-openrc#17]
Please adopt to current changes ...

**Comment by philmmanjaro** [comment]
See also https://github.com/manjaro/release-plan/issues/26

**Comment by philmmanjaro** [comment]
See also https://github.com/manjaro/packages-community/commits/master/bumblebee/PKGBUILD

**Comment by udeved** [comment]
I will test this, I am sitting right now on a bumblebee laptop, all works fine.

**Comment by philmmanjaro** [comment]
Ok, keep me updated.
