### ISSUE TITLE
[bumblebee] openrc package needs to adopt

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-openrc#21]
Please see also: https://github.com/manjaro/packages-community/commit/2c0bb7dc50089e1400026563756ecde82608ed97

**Comment by philmmanjaro** [comment]
Somebody just needs to compile it ...

**Comment by oberon2007** [comment]
ok. will do.

**Comment by oberon2007** [comment]
Done after fixing some typos ;) https://github.com/manjaro/packages-openrc/commit/3395a06fe57c6b5071287bf16c6c955c2db5ed55
