### ISSUE TITLE
bumblebee needs xdm

### ISSUE THREAD

**Issue by zwastik** [manjaro/packages-openrc#22]
Hi. I am using archlinux with openrc from http://systemd-free.org. I was told that systemd-free.org uses manjaro's openrc. When starting bumblebee I get this error message:
 

    sudo rc-service bumblebee start
     * ERROR: bumblebee needs service(s) xdm

Is xdm really necessary? I am using startx for X start. I remember some time ago I got bumblebee working and I had not xdm. Now it doesn't. 

openrc  0.19.1-1
bumblebee-openrc 3.2.1-2

**Comment by udeved** [comment]
Feel free to remove xdm from the initscript, but upstream have it in there.
In other words, in will remain there.
