### ISSUE TITLE
OS detection

### ISSUE THREAD

**Issue by archnous** [manjaro/packages-openrc#23]
Since Arch uses /etc/arch-release could you add an additional elif sourcing it, after the /etc/os-release if block?

**Comment by udeved** [comment]
This would be kind of useless, /etc/arch-release only contains a string.
Wouldn't it be better to use lsb-release and make it a makedepend?

**Comment by cromerc** [comment]
Maybe there is a better solution? The way it is right now it takes the string during compile time, so for example if it is compiled on a manjaro machine and I run it under arch linux it would show the wrong string. I think a better solution would be to detect what is in lsb-release at runtime and display that. Just a thought.

**Comment by archnous** [comment]
@udeved You're right, lsb-release is better. @cromerc's proposal for runtime detection would be the best, but we'd probably bring this upstream.

**Comment by udeved** [comment]
I actually don't really see a reason for runtime detection.
I mean, a package is compiled for a specific distro, hence the branding make flag.
