### ISSUE TITLE
dbus

### ISSUE THREAD

**Issue by archnous** [manjaro/packages-openrc#25]
Why was dbus-openrc-1.10.8 removed from the tree and dbus-openrc init script reactivated? Has the former been replaced by dbus in Manjaro?

**Comment by udeved** [comment]
dbus-openrc-1.10.8 didn't work, it did not start anymore.
I didn't have the time to investigate the reason for now.

So dbus returned to "old" concept" of providing just script on top of default package.

**Comment by udeved** [comment]
I am always forced to react quickly with dbus updates, because of the libdbus.
It had always blocked updates, if there wasn't also a matching dbus-openrc version.

The advantage now is that I don't have to care for for dbus, the disadvantage is, that dbus now has default systemd features, and dbus will only run with eudev-compat package.

**Comment by archnous** [comment]
Yes, I thought as much. I've had my share of rants because of dbus/libdbus breakage.

Anyway, I've fixed the original full dbus-operc package for 1.10.8; the problem lay with the /etc/init.d/dbus script which was changed upstream, please see [the updated /etc/init.d/dbus here](https://gist.github.com/archnous/c3d5dd14e71bc68d6820). The upstream version needs the usual sed substitutions you use in most init scripts for Manjaro/Arch. You can also find the binary package at the [[openrc-eudev repo]](http://netassist.dl.sourceforge.net/project/archopenrc/openrc-eudev/x86_64/dbus-openrc-1.10.8-1-x86_64.pkg.tar.xz) to test. Also, please note this version found and compiled against libaudit in my build box and won't start without community/audit (another bout of rants, hehehe :-) .

So, would you consider re-instating dbus-openrc, either putting audit in depends() or disabling it in configure?

**Comment by udeved** [comment]
Well, at some point, I'd love to have a full set of systemdless base packages with integrated script.
But for now, since we need to use eudev-systemdcompat anyway, I think I will stick for the moment on default dbus.
The original reason I made it a full build was arch upstream changes in 1.10.6 iirc.
So one goal is to get rid of libsystemd, the bottleneck.

**Comment by archnous** [comment]
Ok, I understand. I'll switch to AUR/dbus-openrc for the time being (which was taken from you at 1.10.6 anyway), and see how it goes.

**Comment by Boruch-Baum** [comment]
I'm late to the party, and am only now updating my install, and have held back updating both packages 'libdbus' and 'dbus-openrc'. So far, the libdbus version 1.10-8 isn't required by any other package that I'm running, and nothing seems broken. I have two questions:

1] Is there anything compelling in this update that should convince me I NEED to upgrade for system stability or security?

2] If libdbus is the package giving you maintenance headaches, why not fork it to something like 'libdbus-openrc' and then you can offer the two packages 'dbus-openrc' and 'libdbus-openrc' in sync whenever you are ready?

**Comment by udeved** [comment]
@archnous 

~~~
==> Packages which depend on libsystemd:
core/libdbus 1.10.8-1 [installed]
core/openvpn 2.3.10-1
core/procps-ng 3.3.11-2 (base) [installed]
core/rpcbind 0.2.3-3 [installed]
core/systemd 229-3
core/util-linux 2.27.1-1 (base base-devel) [installed]
extra/ceph 0.94.5-3
extra/libatasmart 0.19-3 [installed]
extra/libgsystem 2015.2-1
extra/libgudev 230-1 [installed]
extra/php-embed 7.0.5-1
extra/python-systemd 231-1
extra/transmission-cli 2.92-1
extra/xf86-input-vmmouse 13.1.0-1 (xorg-drivers xorg)
extra/xorg-server-xnest 1.17.4-2
community/usbip 4.5-1 (linux-tools)
community/uwsgi 2.0.12-7

==> Packages which depend on systemd:
core/crda 3.18-1 [installed]
core/device-mapper 2.02.148-1 (base) [installed]
core/libusb 1.0.20-1 [installed]
core/lvm2 2.02.148-1 (base) [installed]
core/mkinitcpio 19-1 [installed]
core/pcmciautils 018-7 (base) [installed]
extra/accountsservice 0.6.40-2 [installed]
extra/bluez-hid2hci 5.38-3
extra/bluez-plugins 5.38-3
extra/bluez-utils 5.38-3
extra/chromium 49.0.2623.110-1
extra/colord 1.2.12-1 [installed]
extra/cups 2.1.3-1
extra/libinput 1.2.2-1 [installed]
extra/libmbim 1.12.4-1 [installed]
extra/libpulse 8.0-3 [installed]
extra/libwacom 0.18-1 [installed]
extra/lighttpd 1.4.39-2
extra/media-player-info 22-2 [installed]
extra/mesa 11.1.2-1 [installed]
extra/modemmanager 1.4.14-1 [installed]
extra/php-fpm 7.0.5-1
extra/pkgstats 2.3-6
extra/plymouth 1:0.8.8-1
extra/plymouth-dev 0.9.2.r21.gf806843-2
extra/polkit 0.113-4
extra/qtwebkit 2.3.4-4
extra/rtkit 0.11-5 [installed]
extra/subversion 1.9.3-2 [installed]
extra/syslog-ng 3.6.3-2 [installed]
extra/udisks 1.0.5-2
extra/udisks2 2.1.7-1 [installed]
extra/upower 0.99.4-2 [installed]
extra/xf86-input-evdev 2.10.1-1 (xorg-drivers xorg) [installed: 2.10.1-3]
extra/xf86-input-wacom 0.31.0-1
extra/xf86-video-amdgpu 1.0.1-0.1 (xorg-drivers xorg)
extra/xf86-video-ati 1:7.6.1-0.1 (xorg-drivers xorg)
extra/xf86-video-nouveau 1.0.12-0.1 (xorg-drivers xorg)
extra/xf86-video-openchrome 0.3.3-5 (xorg-drivers xorg)
extra/xorg-xdm 1.1.11-6
extra/ypbind-mt 1.38-1
community/cloud-init 0.7.6-2
community/cor 0.1.17-2
community/delayed-hibernation 0.1-1
community/dnscrypt-proxy 1.6.1-1
community/docker 1:1.10.3-1
community/elasticsearch 2.3.0-1
community/envoy 14-2
community/fcgiwrap 1.1.0-4
community/kmscon 8-3
community/liblogging 1.0.5-1
community/mailman 2.1.21-2
community/pcsclite 1.8.15-1
community/playpen 1:13-1
community/qopenvpn 1.3.2-2
community/rabbitmq 3.6.1-1
community/rsyslog 8.17.0-1
community/toxcore 3747-1
community/xlogin 0.r11.a578cf2-1

==> Packages which depend on systemd-tools:
community/percona-server 5.7.11_4-3
~~~

Pretty big list, even with only doing the important ones,
