### ISSUE TITLE
xdg-user-dirs tries to run systemctl

### ISSUE THREAD

**Issue by hubslave** [manjaro/packages-openrc#29]
I got this when updating to 20160504:
```
(367/368) upgrading xdg-user-dirs
/tmp/alpm_LUCl7u/.INSTALL: line 8: systemctl: command not found
error: command failed to execute correctly
```
(have only OpenRC installed)

**Comment by udeved** [comment]
Thats normal, because you don't have systemctl present.
Upstream arch decided to provide a systemd service for xdg.
You can basically ignore it and run xdg-update-dirs or whatever manually.
