### ISSUE TITLE
libudev depends in package tree

### ISSUE THREAD

**Issue by udeved** [manjaro/packages-openrc#30]
Currently, eudev package provides libudev and (e)udev.
Problem: the package tree doesn't know libudev

I would have to be implemented starting with base group.

**Comment by philmmanjaro** [comment]
Be more specific on what the problem here is.

**Comment by udeved** [comment]
There is no problem per se.
I started the issue for a discussion, see the reference.

The real problem is, that libsystemd package includes eg libudev, and all packages depend on the libsystemd.
However, most base packages only require libudev to build or to run.

**Comment by philmmanjaro** [comment]
Ok, that makes sense. However Archlinux decided to only support **systemd** and focused other packages to depend on that decision. In this case you have to check all packages which depends on **libsystemd** and repack them. I don't think we should do that hassle. Currently **libsystemd** has followed files:

```
libsystemd /usr/lib/libnss_myhostname.so.2
libsystemd /usr/lib/libnss_mymachines.so.2
libsystemd /usr/lib/libnss_resolve.so.2
libsystemd /usr/lib/libsystemd.so
libsystemd /usr/lib/libsystemd.so.0
libsystemd /usr/lib/libsystemd.so.0.14.0
libsystemd /usr/lib/libudev.so
libsystemd /usr/lib/libudev.so.1
libsystemd /usr/lib/libudev.so.1.6.4
```
Since **systemd** "owns" also **libudev** everybody switched to that one.

**Comment by udeved** [comment]
I actually don't want to discuss w´the why, its there, and it can only be interpreted as arch linux trying to deliberately make it difficult to replace systemd or libsystemd.
In fact, with eudev-systemdcompat, you got two libudev on the system.
systemd-228 used to still provide a split libsystemd in terms of libraries included.
229 made it a single libsystemd lib. Great.

**Comment by udeved** [comment]
Point being, libudev may still be a lib, but what about a logind alternative? No liblogind any longer to replace.

**Comment by philmmanjaro** [comment]
I don't get you. Please change your provides line to the proper once as Arch did it:
`provides=('libsystemd.so' 'libudev.so')`.

**Comment by udeved** [comment]
Forget about it, I confused something. but I don't get your proposal either. It doesn't make sense, because eudev is free of any systemd provides. Thats provided by eudev-systemdcompat.
Anyway, PKGBUILDs still do not use libudev, no provides or something.

**Comment by philmmanjaro** [comment]
I checked your package:

```
provides=("udev=${_udev_ver}"
"libudev=${_udev_ver}"
'libudev.so')
conflicts=('libudev.so')
```

Seems all fine, so what is the question here?

**Comment by udeved** [comment]
Urgs, I try to be calm and explain.

```
$ yaourt -S --depends libsystemd
==> Packages which depend on libsystemd:
core/dhcpcd 6.10.3-1 (base) [installed]
core/libdbus 1.10.8-1 [installed]
core/openvpn 2.3.11-1
core/procps-ng 3.3.11-2 (base) [installed]
core/rpcbind 0.2.3-3 [installed]
core/systemd 229-3
core/util-linux 2.28-1 (base base-devel) [installed]
extra/ceph 0.94.5-3
extra/gnome-settings-daemon 3.20.1-1 (gnome)
extra/libatasmart 0.19-3 [installed]
extra/libgsystem 2015.2-1
extra/libgudev 230-1 [installed]
extra/php-embed 7.0.7-1
extra/python-systemd 231-1
extra/python2-systemd 231-1
extra/transmission-cli 2.92-1
extra/xf86-input-vmmouse 13.1.0-1 (xorg-drivers xorg)
extra/xorg-server-xnest 1.17.4-2
community/rsyslog 8.18.0-2
community/usbip 4.6-1 (linux-tools)
community/uwsgi 2.0.13-1
```

Most of these packages do not reuqire libsystemd, but they depend on it, because libsystemd package provides libudev. Thats stupid, and it could be made so, that udev providers can coexist, same for logind providers.

Hence I need a custom base-devel group, which unfortunately still pulls eudev-systemdcompat.

**Comment by fbt** [comment]
One way to deal with this is to use the [split libsystemd](https://aur.archlinux.org/pkgbase/libsystemd-standalone) package in AUR. It's pretty much made for this specific reason.

**Comment by udeved** [comment]
Yes, the trouble is, you either need a full set of systemdless packages, including some desktop stuff, or you provide libsystemd library and use repo packages.
Biggest problem is the amount of packages to recompile.

**Comment by fbt** [comment]
Nah, you can use systemd-dummy, which pretty much solves the problem.

**Comment by udeved** [comment]
Which is what eudev-systemdcompat does in manjaro

**Comment by fbt** [comment]
Oh wait, this is a manjaro issue, not an arch one. That's what I get for butting in via a link without actually looking at where the issue is.

**Comment by udeved** [comment]
So you are right, its basically pretty useless to have some *-nosystemd package installed, as long as everything depends on either libsystemd or systemd.

The should only depends on (lib)systemd if they are hard depends, runtime depends.

**Comment by Chrysostomus** [comment]
I wonder if this is again one of those things that would benefit from having a buildserver. I'm a bit skeptic that we could get arch devs to alter dependencies to better work with initsystem that arch does not support.

**Comment by fbt** [comment]
Well if you do ever get to reporting packages with the wrong dependency, then the argument is not “because it makes it harder to support OpenRC”. The argument is as simple as: “These packages depend on something they do actually not depend on. It's wrong”. I actually think they'd agree.

**Comment by udeved** [comment]
I think it is simply unwillingness, my bet is,they gonna close any such bug report.
Too much weight behind the systemd push for them to fix this.
