### ISSUE TITLE
Add snap packages support natively also for OpenRC

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-openrc#31]
I'm currently adding **snap** support for **systemd**, however we should also support it for OpenRC init systems. Check with [Gentoo](https://github.com/zyga/snapd-gentoo) on this one.

**Comment by kozec** [comment]
It doesn't looks like this was actually solved, snapd does literally nothing with openrc :(

**Comment by philmmanjaro** [comment]
Seems it won't happen at all for **openrc**
