### ISSUE TITLE
Dependency breakage

### ISSUE THREAD

**Issue by cromerc** [manjaro/packages-openrc#32]
I just had a nasty dependency breakage from merging the last 5 commits. I am using elogind 2.14 on my system. So when I run sudo pacman -Syu I ended up with a dependency conflict because of the rollback to 2.12 combined with changes making it provide systemd while now eudev-systemdcompat does not provide systemd any longer.

The big issue is that the pacman does not do downgrades when a package in a repo is a lower version that an what is installed. I had to manually downgrade elogind to 2.12 to fix my system.

**Comment by udeved** [comment]
I'll handle downgrade probably with a alpm hook once elogind-219.12 has been readded to repo.
