### ISSUE TITLE
installer installs grub

### ISSUE THREAD

**Issue by sem-geologist** [manjaro/packages-openrc#40]
I want to report the very nasty bug:
The installer have option of not installing grub, **but it ignores the picked option at partition screen (Do not install grub) and installs it anyway overwriting whatever grub version were before**.

Maybe that would not be the problem with simple machine configuration... but on my machine I use quite sophisticated linux raid schemes with my main debian installation there and main grub partly residing there. I use one small non raid partition for trying out distros (debian is getting worse and worse and I am looking for potential distro to migrate to) . The faulty manjaro grub installation made my debian system unbootable. I had to get rescuegrub bootable usb to boot into the debian and fix my main grub (I uninstalled grub in manjaro and I hope it will not come back accidentally with updates?). I am quite experienced with linux (mainly debian, bootloaders, experimenting with linux systems for arm dev boards, some programming skills) and this incident made my brow lift up. However such thing could scare pants out of inexperienced one.

PS.:
I hope manjaro-openrc proves to be right distro for me: I really dislike systemd as it burned me not once but many times. I am not the office camper/gamer/9gag'er/tweete/feed reader/youtube watcher.... my computing tasks is very not standard, mixed (mainly scientific computing, experimenting, developing and adopting new technologies for new methods that's why I need to stay on edge with my system) and I got multiply times into issues with systemd, which caused failure of different components in very important moments publicly making me look like a fool discrediting me and my linux machine. Maybe that monstrosity works for 99% percent of youtube watchers..., but I have work to do and such silly things didn't happened anytime before systemd.

**Comment by aadityabagga** [comment]
Hi @sem-geologist,

I think the current place to report this would be on the Calamares bugtracker (Calamares is the graphical installer used).

I found a similar issue about it: https://calamares.io/bugs/browse/CAL-366

You could also open a ticket on the Manjaro bugtracker: https://bugs.manjaro.org/
