### ISSUE TITLE
elogind todos

### ISSUE THREAD

**Issue by cromerc** [manjaro/packages-openrc#42]
I was curious why elogind is not in the manjaro repos?
I was playing around with making an openrc manjaro iso and wanted to use plymouth with elogind to be able to be able to have a nice boot and shutdown screen.

**Comment by udeved** [comment]
elogind is not in repos, it doesn't play nicely in combination with consolekit.
I use elogind just for testing wayland sessions, until consolekit hopefully fils the gap in regard to logind interface.

**Comment by cromerc** [comment]
I noticed that you have made a lot of work recently with elogind, I haven't merged any of it yet into the http://github.com/arch-openrc/arch-openrc fork since I wanted to see how stable it is. Is this currently up and running well in Manjaro? Are there any known issues?

**Comment by udeved** [comment]
Its running well on manjaro with plasma and lxqt.
Users said, its fine on cinnamon too, in theoiry, even gnome should become sort of working in terms of its logind depend.
I have also sucessfully had a first wayland session on plasma with free drivers however.
All in all, promising, since ck2 dev seems to lack time, and elogind seems actively developed.

I still have an issue to solve in regards to polkit auth agent not registering in plasma, no idea if other agents work.
https://github.com/elogind/elogind/issues/2
Overall, plan is to make elogind replace and upgrade ck packages at some point.

**Comment by cromerc** [comment]
Well I will install manjaro in a virtualbox and give it a go. If it works well I will merge it. However I am not sure if I want to drop ck yet. There might be a lot of people still using it, so it would be nice to leave them a choice to stick with ck if they don't want to use elogind.

**Comment by udeved** [comment]
I keep ck builds here, as failsafe in case we may need them again, or ck2 starts to support logind interface etc...
https://github.com/udeved/packages-testing

**Comment by udeved** [comment]
@cromerc 

Do you build the arch-nosystemd packages in chroot?

I added some library packages and in process to do the bigger ones, namely qt6-base and xorg and drivers. aim is to eliminate libsystemd/systemd depends, and introduce a pure compat package providing libsystemd and systemd for packages which only have these depends but no build time systemd depends.
Usually, its libudev/udev where the put a systemd depend.

**Comment by cromerc** [comment]
Yeah, 100% of the openrc and nosystemd packages are built in chroot.

Here are the scripts I use to build it:
https://github.com/arch-openrc/build-openrc

I don't really like this script very much since it depends on arch's dev
tools which depend on systemd. In particular the script "makechrootpkg"
does not work without systemd's nspawn which they use to mount the chroot
environment. So I have a pure arch linux with systemd running in a
virtualbox which has an openrc chroot environment. So the systemd arch
mounts the openrc chroot then builds the packages in the openrc chroot.

Leave it to the arch dev's to make their software and tools only work with
systemd...

Chris Cromer

**Comment by udeved** [comment]
@cromerc 

You could fork the package part of manjaro-tools and kick out branch settings to make it work with arch.
But I would rather like you to join openrc manjaro subproject. We could share the maintenance.

**Comment by udeved** [comment]
@cromerc 

I got it working now.

sddm-elogind must be compiled against libelogind, and there must not be a libsystemd present in the chroot.
