### ISSUE TITLE
polkit-consolekit corrupt package

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-openrc#45]
Looks like **polkit-consolekit-0.113+29+g3272a98-5-x86_64** package or the signature in unstable repo is corrupt.
https://forum.manjaro.org/t/manjaro-architect-0-8/19291/110

unfortunately I'm not able to find a PKGBUILD for that package.
@udeved can you please rebuild, thanks.

**Comment by udeved** [comment]
https://github.com/udeved/packages-testing

I don't have time until tonight.
ck builds need buildpkg -u flag in case you want to try.

**Comment by oberon2007** [comment]
Thanks. I have pushed a **pkgrel 6**. Will try to check the new package later on an openrc ISO.
