### ISSUE TITLE
Android Phone Problems

### ISSUE THREAD

**Issue by robin0800** [manjaro/packages-openrc#49]
MTP Broken and ADP,  FASTBOOT Broken in "Android debugging"

There is a workaround here
https://forum.manjaro.org/t/openrc-and-elogind-permissions-problem/20574/1

**Comment by udeved** [comment]
I don't have any android package in the repo.

**Comment by robin0800** [comment]
This is a request from here
[](https://forum.manjaro.org/t/stable-update-2017-04-15-kernels-thunderbird-firefox-libreoffice/21784/114url)

**Comment by philmmanjaro** [comment]
@robin0800: are you sure it is a elogind issue?

**Comment by robin0800** [comment]
No I don't think so as the fix? is to /lib/udev/rules.d/69-libmtp and lib/udev/rules.d/51-android.rules. This suggests it is a permissions problem but whether it is udev or pam or something else? it works in systemd and openrc with consolekit but once this is removed it no longer works.

**Comment by udeved** [comment]
I have no idea what you request is.
You copied a udev rule manually, and need to make sure permissions are granted, such as adding your user to proper groups.

**Comment by robin0800** [comment]
Yes all true, but only to make my phone work with elogind the same as it does on systemd nothing needed and openrc + consolekit again nothing needed.
It would be great if nothing was needed for elogind too.

**Comment by udeved** [comment]
I dunno what to fix whatever.

**Comment by udeved** [comment]
Its something on your system, as the elogind devs also could not help you.
