### ISSUE TITLE
More packages on upstream side will move to 'sysusers.d'. How to handle with OpenRC?

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-openrc#56]
It is not News that **Arch** is **systemd-centric**. This situation will get harder by the use of **sysusers.d**. More packages will move to that **systemd-specific** system to add users more dynamically. Latest example is [**Amule**](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/amule&id=822d7e2730c414c79d02843279e39fa9cd0d5f33).

This goes even down to **[filesystem](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/filesystem&id=f13793629ef95b67cbfb315eb5c4c112bd55b0db)** in regard of this issue: [**FS#45196**](https://bugs.archlinux.org/task/45196). A current list of all used UIDs by Arch can be found [here](https://wiki.archlinux.org/index.php/DeveloperWiki:UID_/_GID_Database).

More about **sysusers.d** [here](https://www.freedesktop.org/software/systemd/man/sysusers.d.html).

**Comment by cromerc** [comment]
I have worked out a solution that will help with both arch linux openrc and manjaro openrc.
https://github.com/arch-openrc/opensysusers

This script will mimic systemd's sysusers. There are 2 ways to use it. There is an openrc init script that when started/restarted will add the missing users. The other way is to call it directly with a pacman hook. Basically if a file gets added to /usr/lib/sysusers.d then the hook should call the /usr/bin/sysusers which will add the new users and groups.

There is only 1 part of sysusers.d that is not implemented in the scripts. The type "r" which creates a range of UID and GUID. Personally I don't think it's that necessary for this script based on the fact that none of the files I have in /usr/lib/sysuser.d even use it. But this could always be added later on if necessary. Feel free to make pull requests if you think of ways to improve it.

**Comment by philmmanjaro** [comment]
@cromerc: Looks just fine. Please create the needed PR for the **PKGBUILD**.

**Comment by udeved** [comment]
I'll adopt your build once you have set it to pkgrel=1 and depends are in place @cromerc 
Just say so when its ready. ;)

@cromerc @aadityabagga  we should meet on irc I think to discuss more streamlined efforts on our end.

**Comment by cromerc** [comment]
@udevd The pkgrel was already set to 1, so not sure why ou asked for that.
Depeneds are setup for it now. OpenRC is an optional depend because this works via a pacman hook. The OpenRC script is available but not required.

In which IRC do you guys meet?

**Comment by udeved** [comment]
I propose #manjaro-openrc tonight eventually?

**Comment by aadityabagga** [comment]
I am home now, will join the channel.

**Comment by philmmanjaro** [comment]
@cromerc: thx for the package. It is merged and pushed to **unstable**. Will then adopt more **systemd-centric** stuff by Arch to be more compatible with upstream. With **opensysusers** it should be no issues at all. Since I hold back [dbus changes in filesystem](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/filesystem&id=f13793629ef95b67cbfb315eb5c4c112bd55b0db) this can now be adopted since **opensysusers** is now in our repos.

@udeved: please make **opensysusers** installed by default on **OpenRC** systems to have no issues with the move to **sysusers.d** by upstream in most of the packages, including **dbus**.
