### ISSUE TITLE
Bluez-utils-compat

### ISSUE THREAD

**Issue by karl6994** [manjaro/packages-openrc#62]
I think this is the right place to ask but please forgive me if I am mistaken, is there any way we can get Bluez-utils-compat from the arch AUR to work on OpenRC? That would be super cool! Need it for QTSIXA
Thanks for everything you guys do, Manjaro Linux is awesome!

**Comment by philmmanjaro** [comment]
@karl6994: Manjaro had dropped the support of **OpenRC**. However there is a new project called [Artix Linux](https://artix-linux.github.io/).
