### ISSUE TITLE
[dbus-openrc]

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-openrc#9]
How do we resolve this when building openrc ISOs?
```
error: failed to prepare transaction (conflicting dependencies)
:: dbus-openrc and dbus are in conflict
```

**Comment by philmmanjaro** [comment]
Hmm, with `provides=('dbus-core' "dbus=${pkgver}")` there should be normally no issue ...

**Comment by oberon2007** [comment]
Yes, sounds good! Or would it help to explicitly install >openrc dbus-openrc in shared/Packages ?

**Comment by philmmanjaro** [comment]
Well this is already in the package, so I don't know why this happens. I suggest to do it as you just posted and force to install that version.

**Comment by oberon2007** [comment]
will try

**Comment by oberon2007** [comment]
that works! :)

**Comment by oberon2007** [comment]
https://github.com/manjaro/manjaro-tools-iso-profiles/commit/7b15ace3a9a2b41dd578496f4cb92b0e9a0b444a
